export const Courses = [
  {
    name: 'Web design',
    pic: 'https://i.pinimg.com/736x/5d/e0/93/5de093ef89b1ccb4d72a41b9a88120e5.jpg',
    terms: 'Term 1 * 2025',
  },
  {
    name: 'Multimedia',
    pic: 'https://i.pinimg.com/736x/79/8f/f8/798ff8836bc12fe0df2797ea86c8b653.jpg',
    terms: 'Term 1 * 2025',
  },
  {
    name: 'Networking',
    pic: 'https://i.pinimg.com/736x/15/21/c7/1521c7781296d344caf0426669695a5d.jpg',
    terms: 'Term  1* 2025',
  },
  {
    name: 'A+',
    terms: 'Term 1 * 2025',
  },
  {
    name: 'Database',
    terms: 'Term 1 * 2025',
  },
  {
    name: 'Programing',
    terms: 'Term 1 * 2025',
  },
]

export const admins = [
  {
    name: 'Mustafa',
    email: 'mustafa@gmail.com',
    pass: 'mustafa123',
    img: 'https://github.com/evilrabbit.png',
    role: 'Admin',
  },
  {
    name: 'Suhayb',
    email: 'suhayb@gmail.com',
    pass: 'suahyb123',
    img: 'https://github.com/maxleiter.png',
    role: 'Admin',
  },
  {
    name: 'Nimcaan',
    email: 'nimcaan@gmail.com',
    pass: 'nimcaan123',
    img: 'https://github.com/shadcn.png',
    role: 'Admin',
  },
]

export const uploads = [
  {
    term: 'sep - 2025',
    year: '2025',
    number_of_students: 12,
    subject: 'IT',
  },
  {
    term: 'sep - 2025',
    year: '2025',
    number_of_students: 12,
    subject: 'IT',
  },
  {
    term: 'sep - 2025',
    year: '2025',
    number_of_students: 12,
    subject: 'IT',
  },
  {
    term: 'sep - 2025',
    year: '2025',
    number_of_students: 12,
    subject: 'IT',
  },
]

export const data = [
  {
    Name: 'Maxamed Cali',
    Telephone: '4582190',
    'A+': '88',
    Multimedia: '92',
    'Web Design': '78',
    Networking: '95',
    Database: '85',
    Programming: '90',
    Grade: 'A',
  },
  {
    Name: 'Caasha Xasan',
    Telephone: '3376541',
    'A+': '76',
    Multimedia: '80',
    'Web Design': '88',
    Networking: '79',
    Database: '91',
    Programming: '84',
    Grade: 'B',
  },
  {
    Name: 'Axmed Cumar',
    Telephone: '4987234',
    'A+': '95',
    Multimedia: '90',
    'Web Design': '97',
    Networking: '99',
    Database: '89',
    Programming: '93',
    Grade: 'A',
  },
  {
    Name: 'Xaliimo Aadan',
    Telephone: '3120987',
    'A+': '65',
    Multimedia: '72',
    'Web Design': '70',
    Networking: '68',
    Database: '75',
    Programming: '71',
    Grade: 'C',
  },
  {
    Name: 'C/laahi Jaamac',
    Telephone: '4655432',
    'A+': '88',
    Multimedia: '84',
    'Web Design': '90',
    Networking: '92',
    Database: '86',
    Programming: '94',
    Grade: 'B',
  },
  {
    Name: 'Faadumo Ibraahim',
    Telephone: '3876123',
    'A+': '79',
    Multimedia: '81',
    'Web Design': '75',
    Networking: '80',
    Database: '83',
    Programming: '77',
    Grade: 'C',
  },
  {
    Name: 'Yuusuf Maxamuud',
    Telephone: '4433221',
    'A+': '58',
    Multimedia: '65',
    'Web Design': '60',
    Networking: '62',
    Database: '67',
    Programming: '59',
    Grade: 'D',
  },
  {
    Name: 'Maryan Nuur',
    Telephone: '3219876',
    'A+': '92',
    Multimedia: '94',
    'Web Design': '89',
    Networking: '96',
    Database: '91',
    Programming: '98',
    Grade: 'A',
  },
  {
    Name: 'Cali Geedi',
    Telephone: '4876543',
    'A+': '70',
    Multimedia: '75',
    'Web Design': '72',
    Networking: '71',
    Database: '78',
    Programming: '73',
    Grade: 'C',
  },
  {
    Name: 'Sahra Ismaaciil',
    Telephone: '390875',
    'A+': '83',
    Multimedia: '79',
    'Web Design': '85',
    Networking: '88',
    Database: '81',
    Programming: '86',
    Grade: 'B',
  },
  {
    Name: "Cismaan Daa'uud",
    Telephone: '4123456',
    'A+': '68',
    Multimedia: '71',
    'Web Design': '74',
    Networking: '69',
    Database: '76',
    Programming: '70',
    Grade: 'C',
  },
  {
    Name: 'Khadra Axmed',
    Telephone: '3765432',
    'A+': '90',
    Multimedia: '88',
    'Web Design': '86',
    Networking: '93',
    Database: '87',
    Programming: '91',
    Grade: 'B',
  },
  {
    Name: 'Ibraahim Warsame',
    Telephone: '4567890',
    'A+': '55',
    Multimedia: '50',
    'Web Design': '48',
    Networking: '52',
    Database: '45',
    Programming: '49',
    Grade: 'F',
  },
  {
    Name: 'Hibo Faarax',
    Telephone: '3456789',
    'A+': '98',
    Multimedia: '95',
    'Web Design': '100',
    Networking: '97',
    Database: '96',
    Programming: '99',
    Grade: 'A',
  },
  {
    Name: 'Xasan Shire',
    Telephone: '4321098',
    'A+': '77',
    Multimedia: '74',
    'Web Design': '80',
    Networking: '79',
    Database: '82',
    Programming: '75',
    Grade: 'C',
  },
  {
    Name: 'Nimco Cabdi',
    Telephone: '3543210',
    'A+': '82',
    Multimedia: '85',
    'Web Design': '89',
    Networking: '84',
    Database: '90',
    Programming: '87',
    Grade: 'B',
  },
  {
    Name: 'Cabdiqaadir Sheekh',
    Telephone: '4789012',
    'A+': '64',
    Multimedia: '68',
    'Web Design': '70',
    Networking: '66',
    Database: '72',
    Programming: '65',
    Grade: 'D',
  },
  {
    Name: 'Fartuun Cawaale',
    Telephone: '3678901',
    'A+': '75',
    Multimedia: '78',
    'Web Design': '73',
    Networking: '76',
    Database: '80',
    Programming: '74',
    Grade: 'C',
  },
]
